version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_CREATE_TOPICS: "topic1:3:2,topic2:3:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build: ./docker
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./docker/producer/src:/usr/src:cached
  consumer:
    build: ./docker
    ports:
      - 8081:8080
    tty: true
    volumes:
      - ./docker/consumer/src:/usr/src:cached
